services:
  app:
    build:
      dockerfile: Dockerfile
    container_name: asis-jornada-virtual
    restart: unless-stopped
    volumes:
      - .:/var/www/
    environment:
      - DB_HOST=asistencia-virtual-jornada
      - DB_DATABASE=asistencia-virtual-jornada
      - DB_USERNAME=user
      - DB_PASSWORD=root
#    ports:
#      - "8000:8000"
    depends_on:
      - db

  nginx:
    image: nginx:1.19-alpine
    container_name: asis-jornada-nginx
    restart: on-failure
    ports:
      - "9000:80"
    volumes:
      - .:/var/www/
      - ./nginx:/etc/nginx/conf.d

  db:
    image: mysql:latest
    restart: on-failure
    container_name: asistencia-virtual-jornada
    ports:
      - 3306:3306
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: asistencia-virtual-jornada
      MYSQL_USER: user
      MYSQL_PASSWORD: root
